### ISSUE TITLE
was-registrar: migrate to settings.yml / rails config / shared_config configuration framework

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/was-registrar#24]
We need to setup the `config/settings.yml` configuration framework and migrate constants out of the Rails app configuration.

This issue is connected to https://github.com/sul-dlss/was-registrar/pull/22

**Comment by ndushay** [comment]
and/or use rails config and/or shared_configs

**Comment by ndushay** [comment]
and update devops docs approp.
