### ISSUE TITLE
deploy was-registrar fixes and config updates to prod

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/was-registrar#26]
last deploy was in 2015-10, commit b51036b

We increased the timeout for registration (correctly!) and made the code deployable (it is likely the code used to deploy was never checked in to git -- it was probably only on Ahmed's laptop.

**Comment by ndushay** [comment]
@nullhandle    Are these the right APO objects for was-registrar on prod?

Production has this:
```
config.crawl_apos = 'druid:wr005wn5739,druid:yf700yh0557,druid:xt299pt7593'
config.seed_apo = 'druid:xt299pt7593'
```
Stage has this:
```
config.crawl_apos = 'druid:md569kj5536,druid:vk084mg8119'
config.seed_apo = 'druid:kc214qb2831'
```

**Comment by ndushay** [comment]
blocked by #30 and #29  (i.e. don't do this until those fixes are in)

**Comment by drh-stanford** [comment]
#29 and #30 are fixed now.
