### ISSUE TITLE
was-registrar: exception handling w honeybadger

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/was-registrar#47]
we should

- [x] set up capistrano to notify honeybadger of deploys (there's a gem)
- [x] ensure exceptions are reported to honeybadger
- [x] use slack integrations for the above

 - update devops docs
  - [x] ops concerns
  - [x] checklist

**Comment by ndushay** [comment]
exemplar commit:  

(note this is changing over from squash, but it shows how to add it to cap deploy and how to send exception reports to honeybadger)

https://github.com/sul-dlss/stacks/commit/8142b6d6c42624274c2b49c4dddd861deddb5a6b

- note that for any rescued exceptions, if it's not part of "normal" operations we probably want to notify honeybadger.

- note that shared_configs will need a honeybadger.yml file.  I believe there is a key unique to each app in honeybadger -- I can help you set that up, I think.

**Comment by drh-stanford** [comment]
see https://github.com/sul-dlss/DevOpsDocs/pull/140
